version: '3'
services:
  nginx:
    ports:
      - "80:80"
    volumes: 
      - ./data/nginx-dev:/etc/nginx/conf.d
      - ./web:/var/www/html
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  autismweb:
    environment: 
      - URL=http://192.168.1.9:8000
      